# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b77a729770ef6cbe38abe5ddae30fff60d79e34ee1d66ea78605e5a89a4b69ac3a08224979ab7346beaefab87f5762aecba05a9eb33a2a442cf203b1e3c6503

test:
  secret_key_base: 655706d1387aaefcab363c98b5ca544402bd8cf5197ba87a79910048e9edf08663f8e3fc8f21935ff8478dc057c3b30f29d8d94ae97299cae92c86aff925beac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
